spring.application.name=pedidos
server.address=127.0.0.1
server.port=8081
spring.mvc.problemdetails.enabled=true
spring.jackson.deserialization.accept-float-as-int=false
servicos.estoque-url=${ESTOQUE_URL:http://127.0.0.1:8082}
servicos.pagamentos-url=${PAGAMENTOS_URL:http://127.0.0.1:8083}
servicos.timeout-ms=${SERVICOS_TIMEOUT_MS:2000}
recuperacao.automatica=${RECUPERACAO_AUTOMATICA:true}
recuperacao.intervalo-ms=${RECUPERACAO_INTERVALO_MS:2000}
