spring.application.name=pagamentos
server.address=127.0.0.1
server.port=8083
spring.mvc.problemdetails.enabled=true
simulacao.resultado=${PAGAMENTO_RESULTADO:APROVADO}
simulacao.atraso-resposta-ms=${PAGAMENTO_ATRASO_RESPOSTA_MS:0}
